name:    hextech-graphics
version: "0.2.0"

dependencies:
- base >=4.9.1.0 && <5
- relude ^>= 0.6.0.0
#- require
#- rapid
- time
- extra
- template-haskell
- monad-logger >=0.3 && <0.4
- vector
- flow
- mtl
- lens
- array
- containers
- aeson
- animate
- bytestring
- key-state
- linear
- safe
- safe-exceptions
- sdl2
- sdl2-image
- sdl2-mixer
- sdl2-ttf
- sdl2-gfx
- StateVar
- text
- text-conversions
- random
- ansi-terminal
# Dev
- hlint
- brittany
#- importify
ghc-options: -Wall -O0 #-F -pgmF requirepp
default-extensions:
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- ScopedTypeVariables
- OverloadedStrings
- TemplateHaskell
- MultiParamTypeClasses
- ConstraintKinds
- DeriveGeneric
- RecordWildCards
- StandaloneDeriving
- TupleSections
- TypeApplications
- ViewPatterns
- GADTs
#- CPP
# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  dependencies: 
    base:
        mixin:
          - hiding (Prelude)
    relude:
      mixin:
        - (Relude as Prelude)
    flow:
      mixin:
        - (Flow)


# Runnable executable for our application
executables:
  hextech-graphics:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hextech-graphics

# Test suite
tests:
  hextech-graphics-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - hextech-graphics
    - hspec >=2.0.0
