name:    hextech-graphics
version: "0.1.0"

dependencies:

- base >=4.9.1.0 && <5
- extra
- template-haskell
- monad-logger >=0.3 && <0.4
- vector
- sdl2
- sdl2-image
- text
- flow
- mtl
- lens
# Dev
- hlint
- brittany

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  hextech-graphics:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hextech-graphics

# Test suite
tests:
  hextech-graphics-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - hextech-graphics
    - hspec >=2.0.0
