name:    hextech-graphics
version: "0.1.0"

dependencies:

- base >=4.9.1.0 && <5
- relude ^>= 0.6.0.0
- time
- extra
- template-haskell
- monad-logger >=0.3 && <0.4
- vector
- flow
- mtl
- lens
- array
- containers
- aeson
- animate
- bytestring
- key-state
- linear
- safe
- safe-exceptions
- sdl2
- sdl2-image
- sdl2-mixer
- sdl2-ttf
- sdl2-gfx
- StateVar
- text
- text-conversions
- random
- ansi-terminal
# Dev
- hlint
- brittany
ghc-options: -Wall
default-extensions:
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- ScopedTypeVariables
- OverloadedStrings
- TemplateHaskell
# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  #mixins:
  #- base hiding (Prelude)
  #- relude (Relude as Prelude)


# Runnable executable for our application
executables:
  hextech-graphics:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hextech-graphics

# Test suite
tests:
  hextech-graphics-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - hextech-graphics
    - hspec >=2.0.0
