version: '3.7'

services:

  db:
    image: postgres:12.2-alpine
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes: 
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: ./backend
    depends_on: 
      - db
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - JWT_SECRET
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080

  dbmate:
    image: amacneil/dbmate:v1.8.0
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable 
    depends_on: 
      - db
    volumes:
      - ./backend/db:/db/
    command: --wait up

volumes:
  db-data:
