version: '3.7'

services:

  db:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes: 
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on: 
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - JWT_SECRET
    volumes:
      - ./backend/app:/root/app
      - ./backend/images:/root/images
      - ./backend/src:/root/src
      - ./backend/.env:/root/.env
      - ./backend/graphiql.html:/root/graphiql.html
      - ./backend/schema.graphql:/root/schema.graphql
      - ./backend/package.yaml:/root/package.yaml
      - ./backend/stack.yaml:/root/stack.yaml
    ports:
      - 8080:8080

  dbmate:
    image: amacneil/dbmate:v1.8.0
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable 
    depends_on: 
      - db
    volumes:
      - ./backend/db:/db/
    command: --wait up

volumes:
  db-data:
